version: "3.5"
services:
  app:
    build:
      args:
        user: kolyo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: mailservice
    container_name: mailservice-app
    restart: unless-stopped
    ports:
      - 9000:9000
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mailservice
  nginx:
      image: nginx:alpine
      container_name: mailservice_nginx
      restart: unless-stopped
      ports:
          - 8080:80
      volumes:
          - ./:/var/www
          - ./nginx/conf.d/:/etc/nginx/conf.d
      networks:
          - mailservice
  rabbitmq:
      image: rabbitmq:3.6-management-alpine
      container_name: mailservice_rabbitmq
      ports:
          - "5672:5672"
          - "15672:15672"
      restart: always
  mysql:
      image: mysql:5.7
      container_name: mailservice_mysql
      networks:
        - mailservice
      environment:
        - MYSQL_DATABASE=mailservice
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
networks:
  mailservice:
    driver: bridge
