version: "3.5"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mailservice
    container_name: mailservice-app
    restart: unless-stopped
    ports:
      - 9000:9000
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: 'mysql'
      RABBITMQ_HOST: 'rabbitmq'
      WAIT_HOSTS: rabbitmq:5672, mysql:3306
  nginx:
      image: nginx:alpine
      container_name: mailservice_nginx
      hostname: mailservice.io
      restart: unless-stopped
      ports:
          - 8080:80
      volumes:
          - ./:/var/www
          - ./nginx/conf.d/:/etc/nginx/conf.d
      environment:
        WAIT_HOSTS: rabbitmq:5672, mysql:3306
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15671:15671
      - 15672:15672
      - 5671:5671
      - 5672:5672
  mysql:
      image: mysql:5.7
      container_name: mailservice_mysql
      environment:
        MYSQL_DATABASE: 'mailservice'
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'root'
      volumes:
        - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
